dpws/Happ/urls.py
from django.urls import path, re_path, include
from .views import get_request_class

app_name = 'Happ'

patient_patterns = [
	path('patient-index/', get_request_class(), name='patientIndex'),
	path('make-appointment/', get_request_class(), name='Mappoint'),
	path('view-appointment/', get_request_class(), name='Vappoint'),
	path('emergency/', get_request_class(), name='emergency'),
	path('search/', get_request_class(), name='search'),
	path('<int:doctor_id>/doctor-detail/', get_request_class(), name='doctorDetail'),
	path('info/', get_request_class(), name='info'),
	path('news/', get_request_class(), name='news'),
	path('<int:news_id>/news-detail/', get_request_class(), name='newsdetail'),
	path('online/', get_request_class(), name='online'),
	path('patient-profile/', get_request_class(), name='Pprofile'),
	path('<int:news_id>/news-comments/', get_request_class(), name='newscomm'),
	path('<int:com_id>/edit-comment/', get_request_class(), name='editcom'),
	path('choose-lang/', get_request_class(), name='clang'),
	path('redirect-user/', get_request_class(), name='rediuser'),
	path('pre-appoint/', get_request_class(), name='preappoint'),
	path('<int:apont_id>/try-again', get_request_class(), name='tryagain'),
]

doctor_patterns = [
	path('doctor-index/', get_request_class(), name='doctorIndex'),
	path('add-news/', get_request_class(), name='addnews'),
	path('d-v-appoint/', get_request_class(), name='dvappoint'),
	path('<int:patient_id>/patient-detail/', get_request_class(), name='pdetail'),
	path('notification/', get_request_class(), name='notify'),
	path('view-emergency/', get_request_class(), name='Vemerg'),
	path('dis-list/', get_request_class(), name='dislist'),
	path('<int:dis_id>/discussion/', get_request_class(), name='discussion'),
	path('pnt-online', get_request_class(), name='pntonline'),
	path('doctor-profile/', get_request_class(), name='Dprofile'),
	path('pnt-search/', get_request_class(), name='pntsearch'),
	path('dis-vote/', get_request_class(), name='disvote'),
	path('<int:dis_id>/dis-voted/', get_request_class(), name='voteddis'),
	path('down-qust/', get_request_class(), name='downquest'),
	path('<int:apt_id>/apt-decision/', get_request_class(), name='sdecision'),
]

both_patterns = [
	path('<int:d_id>/<int:p_id>/chat/', get_request_class(), name='dpchat'),
	path('change-pass/', get_request_class(), name='changep'),
	path('survey/', get_request_class(), name='survey'),
	path('profile-pic/', get_request_class(), name='profilepic'),
	path('req-survey/', get_request_class(), name='reqsurv'),
	path('<int:surv_id>/vote-surv', get_request_class(), name='votesurv'),
]

urlpatterns = [
	path('', get_request_class(), name='allindex'),
	path('login/', get_request_class(), name='login'),
	path('forget/', get_request_class(), name='forget'),
	path('sendcode/', get_request_class(), name='sendcode'),
	path('auth-code/', get_request_class(), name='authcode'),
	path('reset-pass/', get_request_class(), name='resetpass'),
	path('logout/', get_request_class(), name='logout'),
	path('signup/', get_request_class(), name='signup'),
	path('unauth/', get_request_class(), name='unauth'),
	path('patient/', include(patient_patterns)),
	path('doctor/', include(doctor_patterns)),
	path('both/', include(both_patterns)),
]

dpws/dpws/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('Happ/', include('Happ.urls')),
    path('admin/', admin.site.urls),
]

dpws/Happ/forms.py
from django import forms
from .models import Question

class UserSignupFrom(forms.Form):
	MARIAL_STAUS = [('Merried','Merried'),('Devorsed', 'Devorsed'), ('Widow', 'Widow'), ('Single','Single')]
	GENDER_CHOICE = [('M', 'Male'), ('F', 'Fimale')]

	first_name = forms.CharField(label='first name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'first name'}))
	last_name = forms.CharField(label='last name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'last name'}))
	age = forms.IntegerField(label='age', widget=forms.NumberInput(attrs={'placeholder': 'your age'}))
	email = forms.EmailField(label='email', max_length=100, widget=forms.EmailInput(attrs={'placeholder': 'you email'}))
	phone = forms.IntegerField(label='phone', widget=forms.NumberInput(attrs={'placeholder': 'phone number'}))
	address = forms.CharField(label='address', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'your address'}))
	username = forms.CharField(label='username', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'username'}))
	gender = forms.CharField(label='gender', max_length=10, widget=forms.Select(choices=GENDER_CHOICE))
	blood_type = forms.CharField(label='blood type', max_length=3, widget=forms.TextInput(attrs={'placeholder': 'blood type'}))
	marial_status = forms.CharField(label='marial status', max_length=100, widget=forms.Select(choices=MARIAL_STAUS))
	password = forms.CharField(label='password', max_length=9, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
	confirm = forms.CharField(label='confirm', max_length=9, widget=forms.PasswordInput(attrs={'placeholder': 'confirm password'}))
	description = forms.CharField(label='status', max_length=400, widget=forms.Textarea(attrs={'placeholder': 'put your health status here'}))

class ChangePassWordForm(forms.Form):
	password = forms.CharField(label='password', max_length=9, widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
	confirm = forms.CharField(label='confirm', max_length=9, widget=forms.PasswordInput(attrs={'placeholder': 'confirm'}))

class SurveryForm(forms.Form):
	question = forms.ModelChoiceField(queryset=Question.objects.all(), empty_label='Choose Question Here')
	answer = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'your answer'}))

dpws/Happ/views.py
from django.shortcuts import render
from .forms import *
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse, Http404, HttpRequest
from django.urls import reverse
from django.contrib.auth.models import User
from .models import *
from .make_forms import *
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm, TextInput, DateTimeInput, HiddenInput, Textarea, DateInput, TimeInput, Select
from django.core.mail import send_mail
from django.db.models import Q
import re
import time
import datetime
# Create your views here.
doctor_list = []
patient_list = []

time_holder = 0
count_request = 1
count_dict = {}

a_group = ['A', 'A+', 'A-']
b_group = ['B', 'B+', 'B-']
ab_group = ['AB', 'AB+', 'AB-']
o_group = ['O', 'O+', 'O-']

def get_template(classname):

	return TemplateManager(classname)()

def inc_time():
	global time_holder
	time_holder += 1
	return time_holder

def get_request_(class_):

	_, name_set = TemplateManager(class_).get_name()
	name = name_set[0]
	if name:
		if len(count_dict) <= 0:
			count_dict.update({name: count_request})
		else:
			if name in count_dict:
				num = count_dict[name]
				count_dict.update({name: num+1})
			else:
				count_dict.update({name: count_request})

		return name, count_dict
	else:
		return

def backup_data(d_base_name, to_path):
	import os
	import platform
	for r, d, f, in os.walk(os.getcwd()):
		if d_base_name in f:
			act = None
			if platform.system() == 'Windows':
				act = 'copy'
			if platform.system() == 'Linux':
				act = 'cp'
			os.system('%s %s\\%s %s' %(act, os.getcwd(), d_base_name, to_path))
			print('Performed: [action: copy] %s %s\\%s %s' %(act, os.getcwd(), d_base_name, to_path))
	del os, platform

def is_string(_str):

	if _str.isalpha():

		return True
	else:
		return False

def is_valid_blood(_str):
	bg = _str.upper()
	if bg in a_group or bg in b_group:
		return True
	elif bg in ab_group or bg in o_group:
		return True
	else:
		return False

def is_valid_phone(_str):
	print(len(str(_str)))
	print(str(_str))
	_str = str(_str)
	if _str.startswith('9') and len(_str) == 9:
		return True
	elif _str.startswith('251') and len(_str) == 12:
		return True
	else:
		return False

def make_form(class_name, attrs):
	
	try:
		fo = Global_Dict_Obj[class_name]
		return fo
	except Exception as e:
		mf = Fill_Form_Field(class_name, attrs)
		exec_obj_as_global(mf.fill())
		fo = Global_Dict_Obj[class_name]
		return fo

class ViewClass(View):

	def _view_class_(self, request):
		url_name = request.resolver_match.url_name
		_, cls_set = TemplateManager.parse_list(url_name)
		view_class = cls_set[-1]()
		
		return view_class

	def get(self, request, *args, **kwargs):
		view_class = self._view_class_(request)
		print('[-X-][requested class view] %s' %(view_class.__class__.__name__))
		
		get = getattr(view_class, 'get')
		try:
			return get(request, *args, **kwargs)
		except Exception as e:
			return HttpResponse('<h1>-- NaN -- </h1>')

	def post(self, request, *args, **kwargs):
		view_class = self._view_class_(request)
		print('[-X-][requested class view] %s' %(view_class.__class__.__name__))

		post = getattr(view_class, 'post')
		try:
			return post(request, *args, **kwargs)
		except Exception as e:
			return HttpResponse('<h1>-- NaN -- </h1>')

class IndexView(View):

	def get(self, request, *args, **kwargs):
		#backup_data('db.sqlite3', 'E:\\Django')
		return render(request, get_template(self), {'login': 'Log In'})

class UserLogin(View):
	passd = Char_Field('password', max_length=9, widget='PasswordInput')
	form = make_form('UserLoginForm', ('username', passd))

	def get(self, request, *args, **kwargs):
		login_form = self.form()
		
		return render(request, get_template(self), {'login_form': login_form})

	def post(self, request, *args, **kwargs):
		login_form = self.form(request.POST)

		if login_form.is_valid():
			
			username = login_form.cleaned_data.get('username')
			password = login_form.cleaned_data.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				try:
					global time_holder

					doctor_username = Doctor.objects.filter(username=username)
					patient_username = Patient.objects.filter(username=username)
					if doctor_username.exists():

						doctor_list.append(username)
						print('[-X-]',datetime.datetime.now(),': Action[login]: user:', username)
						time_holder -= time_holder
						return HttpResponseRedirect(reverse('Happ:doctorIndex'))
					elif patient_username.exists():
						patient_list.append(username)
						print('[-X-]',datetime.datetime.now(),': Action[login]: user:', username)
						time_holder -= time_holder
						return HttpResponseRedirect(reverse('Happ:patientIndex'))
					else:
						return HttpResponseForbidden(HttpResponse('you are not authorized here'))
				except Exception as e:
					pass
			else:
				tryed = inc_time()

				if tryed >= 2:
					time.sleep(tryed)
				if tryed >= 5:
					#global time_holder
					time_holder -= tryed
					return HttpResponseForbidden(HttpResponse('<center><h1>Too many trial</h1> \
						<p>if you forget your password try reseting <a href="/Happ/forget/">here</a> \
						or contact the adminstrator </p></center>'))

				cls_name, di = get_request_(self)
				num = di[cls_name]
				if num >= 4:
					count_dict[cls_name] = 0
					return render(request, get_template(self), {'login_form': login_form, 'forget': 'forget password ?'})
				return render(request, get_template(self), {'login_form': login_form, 'wrong_user': 'Wrong username or password'})
		else:
			return render(request, get_template(self), {'login_form': login_form, 'invalid': 'Invalid input'})

class ForgetPassword(View):
	mf = Email_Field('email', placeholder='email')
	form = make_form('ForgetPasswordForm', (mf,))

	def get(self, request, *args, **kwargs):
		forget_form = self.form()
		return render(request, get_template(self), {'forget_form': forget_form})

	def post(self, request, *args, **kwargs):
		forget_form = self.form(request.POST)

		if forget_form.is_valid():
			email = forget_form.cleaned_data.get('email')

			try:
				patient_obj = Patient.objects.get(email=email)
				request.session['email'] = email
				return render(request, get_template(self), {'forget_form': forget_form, 'patient_obj': patient_obj})
			except Exception as e:
				try:
					doctor_obj = Doctor.objects.get(email=email)
					request.session['email'] = email
					return render(request, get_template(self), {'forget_form': forget_form, 'doctor_obj': doctor_obj})
				except Exception as e:
					return render(request, get_template(self), {'forget_form': forget_form, 'user_not_found': 'There is no user registered with this number'})

class SendCode(View):

	def get(self, request, *args, **kwargs):
		return HttpResponseRedirect(reverse('Happ:login'))
		
	def post(self, request, *args, **kwargs):
		yes_it_is_me = request.POST['yes_it_is_me']
		email = request.session['email']
		code = random_vari_num(5)
		try:
			pnt_obj = Patient.objects.get(email=email)
			send_mail('test mail', str(code), 'nhattywap123@gmail.com', [pnt_obj.email], fail_silently=False)
			del request.session['email']
			request.session['_code_'] = code
			request.session['_username_'] = pnt_obj.username
			return HttpResponseRedirect(reverse('Happ:authcode'))
		except Exception as e:
			try:
				doc_obj = Doctor.objects.get(email=email)
				send_mail('Happ mail', str(code), 'nhattywap123@gmail.com', [doc_obj.email], fail_silently=False)
				del request.session['email']
				request.session['_code_'] = code
				request.session['_username_'] = doc_obj.username
				return HttpResponseRedirect(reverse('Happ:authcode'))
			except Exception as e:
				return render(request, get_template(self), {'unknown_user': 'you are not authorized idividual'})

class AuthenCode(View):
	i_field = Integer_Field('code', placeholder='enter the code')
	form = make_form('ResetForm', (i_field,))

	def get(self, request, *args, **kwargs):
		reset_form = self.form()
		if not request.session.get('_code_'):
			return HttpResponseRedirect(reverse('Happ:login'))

		return render(request, get_template(self), {'reset_form': reset_form})

	def post(self, request, *args, **kwargs):
		reset_form = self.form(request.POST)

		if reset_form.is_valid():
			code = reset_form.cleaned_data.get('code')
			_code_ = request.session['_code_']

			if int(code) == int(_code_):
				del request.session['_code_']
				return HttpResponseRedirect(reverse('Happ:resetpass'))
			else:
				return render(request, get_template(self), {'reset_form': reset_form, 'invalid_code': 'the code you entered is invalid'})


class ResetPassword(View):
	form = ChangePassWordForm

	def get(self, request, *args, **kwargs):
		reset_pass_form = self.form()

		if not request.session.get('_username_'):
			return HttpResponseRedirect(reverse('Happ:login'))

		return render(request, get_template(self), {'reset_pass_form': reset_pass_form})

	def post(self, request, *args, **kwargs):
		reset_pass_form = self.form(request.POST)
		_username_ = request.session['_username_']
		user = User.objects.get(username=_username_)

		if reset_pass_form.is_valid():
			new_pass = reset_pass_form.cleaned_data.get('password')
			conf_new = reset_pass_form.cleaned_data.get('confirm')

			if new_pass == conf_new:
				if len(new_pass) >= 8:
					match_1 = re.findall((r"\D\w+\d+"), new_pass)
					match_2 = re.findall((r"\d+\w+\D"), new_pass)
					if match_1 or match_2:
						same_pass = user.check_password(new_pass)
						
						if same_pass:
							return render(request, get_template(self), {'reset_pass_form': reset_pass_form, 'old_pass': 'The new password is the same as the old'})

						user.set_password(new_pass)
						user.save()
						del request.session['_username_']

dpws/Happ/templates/Happ/both_view.html
{% extends "Happ/both_base.html" %}
{% load static %}

{% block header %}
<style type="text/css">
	.header-container {
		
		width: 100%;
		margin: 0px;
	}
	.header-container .header {
        width: 100%;
        text-align: center;
        background: #000;
        padding: 5px;
    }
    .header-container .header p {
        position: relative;
      font-family: sans-serif;
      text-transform: uppercase;
      font-size: 1em;
      letter-spacing: 4px;
      overflow: hidden;
      background: linear-gradient(90deg, #000, #fff, #000);
      background-repeat: no-repeat;
      background-size: 80%;
      animation: animate 2s linear infinite;
      background-clip: text;
      -webkit-background-clip: text;
      -webkit-text-fill-color: rgba(255, 255, 255, 0.1);
    }
    .header-container .header h1{
      position: relative;
      font-family: sans-serif;
      text-transform: uppercase;
      font-size: 1em;
      letter-spacing: 4px;
      overflow: hidden;
      background: linear-gradient(90deg, #000, #fff, #000);
      background-repeat: no-repeat;
      background-size: 80%;
      background-clip: text;
      -webkit-background-clip: text;
      -webkit-text-fill-color: rgba(255, 255, 255, 0.1);
    }
</style>
<div class="header-container">
<div class="header">    
        <p>Well Come To</p>
        <h1>ONLINE HOSPITAL USER SERVICE</h1>
    </div>
 </div>
{% endblock %}

{% block content %}

<!-- -------------------------------CHAT VIEW--------------------------- -->
{% if chat_form %}

<style type="text/css">
.header-container {
	position: fixed;
}
.header-container .header h1 {
	font-size: 1em;
}
.header-container .header p {
	font-size: 1em;
}
.main-container {
	margin-left: 20%;
	margin-right: 20%;
	padding-top: 310px;
	padding-bottom: 30px;
	border: 1px solid #889933;
	border-radius: 10px;
	background: linear-gradient(-90deg, #000, #123456);
}

.main-box {
	margin: 10px;
	border:1px solid #558abb;
	border-radius: 80px;
	width: 40%;
	background-color: rgba(0, 0, 0, 0.25);
	margin-top: 10px;
	box-shadow: 5px 5px 5px rgba(66,66,66,0.7);
	margin: 20px;
}
.main-box p.message {
	font-family: Roboto, sans-serif;
	font-size: 15px;
	padding-left: 25px;
	color: #f1f1f1;
}
.main-box p.date {
	margin-left: 50%;
	font-size: 15px;
	color: #f1f1f1;
	font-style: italic;
}
.user-name {
	width: 90%;
	color: #aaa;
	margin-left: 18px;
	margin-top: 2px;
	font-weight: bold;
	padding-top: 5px;
	text-align: right;
}
.post-chat-box {
	width: 100%;
	position: fixed;
	padding: 5px;
	margin-top: 88px;
	/*margin-left: 290px;*/
	border-bottom-right-radius: 10px;
	border-bottom-left-radius: 10px;
	background: #fff;
	color: #000;
	border: 1px solid #000;
}
.post-chat-box input[type="text"] {
	padding: 10px;
	width: 75%;
	border-radius: 5px;
	border: 2px solid #dee2e6;
}
 .post-chat-box input[type="submit"]{
	padding: 12px;
	padding-left: 35px;
	padding-right: 35px;
	border-radius: 5px;
	border: none;
	background: #123456;
	color: #f1f1f1;
}
@media only screen and (max-width: 770px) {
	.post-chat-box {
		margin-left: auto;
		width: 90%;
	}
	.post-chat-box input[type="text"] {
		width: 45%;
	}
	.main-container {
		margin-left: 20px;
		margin-right: 20px;
	}
}
</style>


<div class="post-chat-box">
{% if ch_lang %}

<div class="ch-lang">
	<p>language: {{ ch_lang }}</p>
</div>	
{% endif %}
<form action="{% url 'Happ:dpchat' d_id p_id %}" method="post">
	{% csrf_token %}
	{{ chat_form.non_field_errors }}
	{% for field in chat_form %}
	<span>
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</span>
	{% endfor %}
	<input type="submit" name="btn" value="send">
</form>
</div>
{% endif %}
{% if all_chats %}
<div class="main-container">

	{% for chat in all_chats %}
	<div class="main-box" id="{{ chat.someone}}_cbox">
	
		<p class="message">{{ chat.message }}</p>
		<p class="date">{{ chat.date }}</p>
	
	</div>
	<script type="text/javascript">
		box = document.getElementById('{{ chat.someone }}_cbox');

		if ("{{ chat.someone }}_cbox" != "{{ request.user.username }}_cbox") {
			div_2 = document.createElement('div');
			div_2.setAttribute("style", "background: #000;color: #f1f1f1;border: 1px solid #558abb;width: 9%;padding: 10px;border-radius: 80px;");
			text_2 = document.createTextNode('{{ chat.someone }}');
			div_2.appendChild(text_2);
			f_child_2 = box.lastChild;
			box.insertBefore(div_2, f_child_2.nextSibiling);
		}
		else {
		box.style.margin = "0px 0px 10px 440px";
		box.style.background = "rgba(58, 238, 178, 0.14)";
		_div = document.createElement('div');
		_div.setAttribute("style", "background: #000;margin-left: 300px;color: #f1f1f1;border: 1px solid #558abb;width: 9%;padding: 10px;border-radius: 80px;");
		_txt = document.createTextNode("you");
		
		_div.appendChild(_txt);
		f_child = box.lastChild;
		box.insertBefore(_div, f_child);
		}
		box.id = "cbox";
	</script>

	{% endfor %}
</div>
{% endif %}


<style type="text/css">
	.form-gen-container {
        border: 1px solid #dee2e6;
        width: 50%;
        margin-left: 300px;
        margin-top: 50px;
        padding: 10px;
        background-color: #fff;
        box-shadow: 2px 0 15px rgba(0, 0, 0, 0.25);
        border-radius: 5px;
    }
    .form-gen-container .gen-form-input input, select{
      width: 50%;
      margin: 10px;
      box-sizing: border-box;
      box-shadow: none;
      outline: none;
      border: 1px solid #999;
      border-radius: 5px;
      padding: 8px 20px 8px 8px;
      font-size: 1rem;
      font-weight: 300;
      color: #000;
      transition: all 0.3s ease-in-out;
    }
    .form-gen-container .gen-form-input input:focus {
        box-shadow: 2px 2px 0px 0px #123;
    }

    .form-gen-container input[type="submit"]{
        width: 20%;
        color: #fff;
        padding: 10px;
        border: 0px;
        border-radius: 5px;
        margin: 10px;
        background: #123456;
        transition: all 0.3s ease-in-out;
    }
    .form-gen-container input[type="submit"]:hover {
        width: 30%;
        border-radius: 15px;
        box-shadow: 2px 0 15px rgba(0, 0, 0, 0.25);
    }
</style>
<!-- ---------------------------CHANGE PASSWORD VIEW---------------------- -->

{% if ch_p_form %}

<div class="form-gen-container">
<form action="{% url 'Happ:changep' %}" method="post">
	{% csrf_token %}
	{{ ch_p_form.non_field_errors }}
	{% for field in ch_p_form %}
	<div class="gen-form-input">
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</div>
	{% endfor %}
	<input type="submit" name="btn" value="Change">
</form>
{{ too_short }}
{{ p_no_match }}
{{ invalid }}
{{ must_be }}
{{ old_pass }}
</div>
{% endif %}

<!-- -----------------------SURVEY VIEW-------------------------------- -->
{% if survey_form %}
<div class="form-gen-container" style="padding-top: 120px;">
<form action="{% url 'Happ:survey' %}" method="post">
	{% csrf_token %}
	{{ survey_form.non_field_errors }}
	{% for field in survey_form %}
	<div class="gen-form-input">
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</div>
	{% endfor %}
	<input type="submit" name="btn" value="send">
</form>
{{ already }}
<p>request survey <a href="{% url 'Happ:reqsurv' %}">here</a></p>
</div>
{% endif %}

<!-- ---------------------------REQSURVEY------------------------------- -->
{% if high_sur_title %}
<div class="high-list-container">
	<div class="high-list">
<h3>High Voted Titles</h3>
<ul>
	{% for s_title in high_sur_title %}
	<li>
		<span class="h-title">{{ s_title.title }}</span>
		<span class="sepa-line">||</span>
		<span class="h-vote">{{ s_title.vote }}</span>
	</li>
	{% endfor %}
</ul>
</div>
{% endif %}

{% if reque_surv_list %}
<div class="vote-container">
<ul>
	{% for reque in reque_surv_list %}
	<li><div class="dis-auth-con">
		<div class="dis-auth">Author: {{ reque.surv_title.author }}
		</div> 
		<ul>
			<li> title: {{ reque.surv_title.surv_title }}</li> 
			<li>votes: {{ reque.vote }}</li>
		</ul>
	</div>
	<form action="{% url 'Happ:votesurv' reque.id %}" method="post">
		{% csrf_token %}
		<input type="submit" name="voted" value="vote">
	</form> <form action="{% url 'Happ:votesurv' reque.id %}" method="post">
		{%csrf_token %}
		<input type="submit" name="unvoted" value="unvote">
	</form></li>
	{% endfor %}
</ul>
{% if alreadey_voted_s %}<p>{{ alreadey_voted_s }}</p>{% endif %}
{% if alreadey_unvoted_s %}<p>{{ alreadey_unvoted_s }}</p>{% endif %}
</div>
</div>
{% endif %}


{% if surv_req_form %}
<div class="form-gen-container">
<form action="{% url 'Happ:reqsurv' %}" method="post">
	{% csrf_token %}
	{{ surv_req_form.non_field_errors }}
	{% for field in surv_req_form %}
	<div class="gen-form-input">
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</div>
	{% endfor %}
	<input type="submit" name="btn" value="request">
</form>
</div>
{% if alreadey_token_surv %}<p>{{ alreadey_token_surv }}</p>{% endif %}
{% endif %}

<!-- ---------------------DOWNSURVEY---------------------------------- 

{% if down_form %}
<br><hr>
<form action="{% url 'Happ:downquest' %}" method="post">
	{%csrf_token %}
	{{ down_form.non_field_errors }}
	{% for field in down_form %}
	<div>
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</div>
	{% endfor %}
	<input type="submit" name="btn" value="download">
</form>
<br><hr>

{% endif %} -->
<!-- -------------------------PROFILEPIC------------------------------ -->

{% if pic_form %}
<div class="form-gen-container">
<form enctype="multipart/form-data" action="{% url 'Happ:profilepic' %}" method="post">
	{% csrf_token %}
	{{ pic_form.non_field_errors }}
	{% for field in pic_form %}
	<div class="gen-form-input">
		{{ field.errors }}
		{{ field.label_tag }}
		{{ field }}
	</div>
	{% endfor %}
	<input type="submit" name="pic-btn" value="upload">
</form>
{% if invalid %}<p>{{ invalid }}</p>{% endif %}
</div>
{% endif %}
{% endblock %}

dpws/Happ/templates/Happ/unauth.html
{% extends "Happ/base.html" %}

{% block content %}
<center>
{% if title %}<h1>{{ title }}</h1>{% endif %}
{% if desc %}<p>{{ desc }}</p>{% endif %}
</center>
{% endblock %}